spring.datasource.url=jdbc:h2:mem:recette;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.h2.console.enabled=true
server.port=8080
jwt.secret=wasfatiSecretKey2024VeryLongSecretKeyForHMACSHA256Algorithm
jwt.expiration=86400000
springdoc.swagger-ui.path=/swagger-ui.html
